[package]
name = "cruster-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
cruster-core = { workspace = true }
cruster-kube = { workspace = true }
cruster-tui = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
is-terminal = { workspace = true }
k8s-openapi = { workspace = true }
kube = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "test-util"] }
