[package]
name = "cruster-bin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "cruster"
path = "src/main.rs"

[[bench]]
name = "startup"
harness = false
path = "../../benches/startup.rs"

[dependencies]
cruster-core = { workspace = true }
cruster-kube = { workspace = true }
cruster-tui = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
kube = { workspace = true }
k8s-openapi = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
